name: jagomart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.1.3+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  # Official animations package providing Material Design transitions
  animations: ^1.1.2
  dio: ^3.0.9
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4
  themify_flutter: ^1.0.0
  curved_navigation_bar: ^0.3.4
  google_fonts: ^1.1.1
  awesome_dialog: ^1.2.1
  auto_size_text: ^2.1.0
  sliver_tools: ^0.1.10+1 
  flutter_swiper: ^1.1.6
  flutter_rating_bar: ^3.0.1+1
  google_maps_flutter: ^1.0.6
  sqflite: ^1.3.2+2
  intl: ^0.16.1
  geolocator: ^6.1.13
  geocoding: ^1.0.5
  path_provider: ^1.6.14
  url_launcher: ^5.7.10
  flutter_open_whatsapp: ^0.1.2
  flutter_phone_direct_caller: ^1.0.1

  shimmer: ^1.0.1
  flutter_staggered_grid_view: ^0.3.3
  fluttertoast: ^4.0.1
  flutter_html: ^1.0.2
  photo_view: ^0.10.3
  sweetalert: ^0.0.1
  badges: ^1.1.0
  loading_indicator: ^1.1.0
  modal_progress_hud: ^0.1.3
  flutter_form_bloc: ^0.19.0
  barcode_flutter: ^1.1.2
  ticket_pass_package: ^0.1.0
  share: ^0.6.5+4
  image_picker: ^0.6.7+12
  timeline_tile: ^1.0.0
  onesignal_flutter: ^2.6.2
  android_intent_plus: ^0.4.1
  pin_code_fields: ^5.0.0
  in_app_update: ^1.1.15
  rxdart: ^0.24.0
  flutter_shine: ^0.0.5
  flutter_inappwebview: ^4.0.0+4
  transparent_image: ^1.0.0
  flutter_custom_tabs: ^0.6.0
  flutter_link_preview: ^1.5.6
  emoji_picker: ^0.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# Settings for the flutter_native_splash package
# run flutter pub run flutter_native_splash:create to update splash screen
flutter_native_splash:
  image: images/store.png
  color: "4caf50"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
   - images/
   - images/tracking/
   - assets/notifcustome.mp3
   - assets/otp.flr
   - assets/maintenance.flr
   - assets/Empty.flr
   - assets/Clock.flr
   - assets/signin.flr
   - assets/options.flr
   - assets/no_favorites.flr
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # # example:
  # fonts:
  # - family: google
  #   fonts: 
  #     - asset: fonts/Product-Sans-Regular.ttf
  #     - asset: fonts/Product-Sans-Bold.ttf
  #       weight: 400
  #     - asset: fonts/Product-Sans-Bold-Italic.ttf
  #       style: italic

  # - family: koodak
  #   fonts:
  #     - asset: fonts/koodak.ttf
  #       weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
